## Q1

In [1]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1 + 2)
print(arr1 * 3)
print(arr1 / 2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


## Q2

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val_x, counts_x = np.unique(x, return_counts=True)
most_freq_x = val_x[np.argmax(counts_x)]
indices_x = np.where(x == most_freq_x)[0]
print(most_freq_x)
print(indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val_y, counts_y = np.unique(y, return_counts=True)
most_freq_y_vals = val_y[counts_y == counts_y.max()]
for val in most_freq_y_vals:
    indices_y = np.where(y == val)[0]
    print(val)
    print(indices_y)

[5 4 6 3 2 1]
1
[0 5 7 8 9]
1
[0 1 2]
3
[4 8 9]


## Q3

In [3]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr3[0, 1])
print(arr3[2, 0])

20
70


## Q4

In [4]:
dhruv = np.linspace(10, 100, 25)
print(dhruv.ndim)
print(dhruv.shape)
print(dhruv.size)
print(dhruv.dtype)
print(dhruv.nbytes)

transpose_reshape = dhruv.reshape(25, 1)
print(transpose_reshape)

print(dhruv.T)

1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


## Q5

In [5]:
ucs420_dhruv = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]).reshape(3, 4)
print(np.mean(ucs420_dhruv))
print(np.median(ucs420_dhruv))
print(np.max(ucs420_dhruv))
print(np.min(ucs420_dhruv))
print(np.unique(ucs420_dhruv))

reshaped_ucs420_dhruv = ucs420_dhruv.reshape(4, 3)
print(reshaped_ucs420_dhruv)

resized_ucs420_dhruv = np.resize(ucs420_dhruv, (2, 3))
print(resized_ucs420_dhruv)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
